services:
  kwil-gateway:
    container_name: kwil-gateway
    hostname: kwil-gateway
    volumes:
      - type: bind
        # bind the file to the container
        source: ../../.build/kgw
        target: /app/kgw
      - type: bind
        source: ../gateway/kgw-config.pkl
        target: /app/kgw-config.pkl

    build:
      dockerfile: ../gateway/gateway.dockerfile

    ports:
      - "8090:8090"
    networks:
      - tsn-network
    environment:
      SESSION_SECRET: ${SESSION_SECRET:-not_secret}
      DOMAIN: https://localhost:443
      # to test the dev-network, use the following values:
      # BACKENDS: tsn-db-1:8080,tsn-db-2:8080
      # CHAIN_ID: tsn-local
      BACKENDS: ${BACKENDS:-tsn-db:8080}
      CHAIN_ID: ${CHAIN_ID:-truflation-staging}
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS}
      ALLOW_DEPLOY_DB: true

  nginx:
    container_name: nginx
    hostname: nginx
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./default.conf.template
        target: /etc/nginx/templates/default.conf.template
      - type: bind
        source: ./certs
        target: /etc/nginx/certs
    environment:
      - DOMAIN_NAME=localhost
    depends_on:
      - kwil-gateway
    networks:
      - tsn-network

networks:
  tsn-network:
    driver: bridge
    name: tsn-network
    # should already be created by compose.yaml
    external: true
