# Define common YAML anchors for Postgres and tn-db
x-postgres-common: &postgres_common
  environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    interval: 5s
    timeout: 5s
    retries: 5
  networks:
    - tn-network
  shm_size: 2G
  restart: unless-stopped

x-postgres-data: &postgres_data
  type: volume
  target: /var/lib/postgresql/data
  volume:
    nocopy: true

x-tn-db-build: &tn_db_build
  context: ../..
  dockerfile: ./deployments/Dockerfile
  args:
    - CHAIN_ID=${CHAIN_ID:-trufnetwork-dev}

x-common-logging: &common_logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "2"
    tag: "{{.Name}}"

services:
  kwil-postgres-1:
    image: "kwildb/postgres:16.8-1"
    ports:
      - "5432:5432"
    <<: *postgres_common
    volumes:
      - <<: *postgres_data
        source: data-kwil-postgres-1

  kwil-postgres-2:
    image: "kwildb/postgres:16.8-1"
    ports:
      - "5433:5432"
    <<: *postgres_common
    volumes:
      - <<: *postgres_data
        source: data-kwil-postgres-2

  tn-conf:
    container_name: tn-conf
    image: "tn-conf:local"
    build:
      context: ../..
      dockerfile: ./deployments/dev-net/network-conf.dockerfile
      args:
        - CHAIN_ID=${CHAIN_ID:-trufnetwork-dev}
        - NUMBER_OF_NODES=2
        - CONFIG_PATH=/app/config
        - HOSTNAMES=tn-db-1,tn-db-2
    volumes:
      - type: volume
        source: tn-conf
        target: /app/config
    logging: *common_logging

  tn-db-1:
    container_name: tn-db-1
    hostname: tn-db-1
    build: *tn_db_build
    environment:
      - CONFIG_PATH=/root/.kwild/node0/
      - KWILD_DB_HOST=kwil-postgres-1
      - KWILD_APP_HOSTNAME=tn-db-1
      - KWILD_CHAIN_P2P_EXTERNAL_ADDRESS=http://tn-db-1:26656
      - DB_OWNER=${DB_OWNER:-0x4710A8D8F0D845da110086812a32De6d90d7ff5C}
    ports:
      - "50051:50051"
      - "8080:8080"
      - "8484:8484"
      - "26656:26656"
      - "26657:26657"
    depends_on:
      tn-conf:
        condition: service_completed_successfully
      kwil-postgres-1:
        condition: service_healthy
    networks:
      - tn-network
    volumes:
      - type: volume
        source: tn-conf
        target: /root/.kwild
    logging: *common_logging
    restart: unless-stopped

  tn-db-2:
    container_name: tn-db-2
    hostname: tn-db-2
    build: *tn_db_build
    environment:
      - CONFIG_PATH=/root/.kwild/node1/
      - KWILD_DB_HOST=kwil-postgres-2
      - KWILD_APP_HOSTNAME=tn-db-2
      - KWILD_CHAIN_P2P_EXTERNAL_ADDRESS=http://tn-db-2:26656
      - DB_OWNER=${DB_OWNER:-0x4710A8D8F0D845da110086812a32De6d90d7ff5C}
    ports:
      - "8485:8484"
      - "26658:26657"
    depends_on:
      tn-conf:
        condition: service_completed_successfully
      kwil-postgres-2:
        condition: service_healthy
    networks:
      - tn-network
    volumes:
      - type: volume
        source: tn-conf
        target: /root/.kwild
    logging: *common_logging
    restart: unless-stopped

networks:
  tn-network:
    driver: bridge
    name: tn-network

volumes:
  data-kwil-postgres-1:
  data-kwil-postgres-2:
  tn-conf: