services:
  indexer-caddy:
    image: "caddy:latest"
    hostname: indexer-caddy
    ports:
      - "81:81"
      - "444:444"
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
    networks:
      - tn-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

  indexer-postgres:
    image: "postgres:latest"
    hostname: indexer-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=indexer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # persis data
    volumes:
      - type: volume
        source: data-indexer
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    networks:
      - tn-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"

  indexer:
    hostname: indexer
    restart: unless-stopped
    build:
      context: ../..
      dockerfile: deployments/indexer/indexer.dockerfile
    environment:
      NODE_RPC_ENDPOINT: ${NODE_RPC_ENDPOINT:-http://tn-db-1:8484}
      KWIL_PG_CONN: ${KWIL_PG_CONN:-postgresql://kwild@kwil-postgres:5432/kwild?sslmode=disable}
      INDEXER_PG_CONN: "postgresql://postgres:postgres@indexer-postgres:5432/indexer?sslmode=disable"
    ports:
      - "1337:1337"
    networks:
      - tn-network
    depends_on:
      indexer-postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1337/v0/swagger" ]
      interval: 5s
      retries: 5
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
        tag: "{{.Name}}"
    volumes:
      - ${INDEXER_BINARY_PATH:-.build/kwil-indexer}:/app/kwil-indexer

networks:
  tn-network:
    external: true
    driver: bridge
    name: tn-network
volumes:
  data-indexer: